# Generated by Django 5.2.7 on 2025-11-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniuser',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni')], default='Alumni', max_length=10),
        ),
    ]
